### ISSUE TITLE
dimension mismatch

### ISSUE THREAD

**Issue by vijaysamula** [hoangcuongbk80/Object-RPE#1]
Hi guys,
I am testing the YCB dataset with ROS. I have encountered the following error when I tried to test. The error is in PoseRineNet size mismatch for feat.conv5.weight: copying a param of torch.
RuntimeError: Error(s) in loading state_dict for PoseRefineNet:
**Size([512, 384, 1]) from the checkpoint, where the shape is torch.Size([512, 256, 1]) in current model.
size mismatch for conv1_r.bias: copying a param of torch.Size([512]) from checkpoint, where the shape is torch.Size([640]) in current model.
size mismatch for conv1_r.weight: copying a param of torch.Size([512, 1024]) from checkpoint, where the shape is torch.Size([640, 1408, 1]) in current model.
size mismatch for conv1_t.bias: copying a param of torch.Size([512]) from checkpoint, where the shape is torch.Size([640]) in current model.
size mismatch for conv1_t.weight: copying a param of torch.Size([512, 1024]) from checkpoint, where the shape is torch.Size([640, 1408, 1]) in current model.
size mismatch for conv2_r.bias: copying a param of torch.Size([128]) from checkpoint, where the shape is torch.Size([256]) in current model.
size mismatch for conv2_r.weight: copying a param of torch.Size([128, 512]) from checkpoint, where the shape is torch.Size([256, 640, 1]) in current model.
size mismatch for conv2_t.bias: copying a param of torch.Size([128]) from checkpoint, where the shape is torch.Size([256]) in current model.
size mismatch for conv2_t.weight: copying a param of torch.Size([128, 512]) from checkpoint, where the shape is torch.Size([256, 640, 1]) in current model.
size mismatch for conv3_r.bias: copying a param of torch.Size([84]) from checkpoint, where the shape is torch.Size([128]) in current model.
size mismatch for conv3_r.weight: copying a param of torch.Size([84, 128]) from checkpoint, where the shape is torch.Size([128, 256, 1]) in current model.
size mismatch for conv3_t.bias: copying a param of torch.Size([63]) from checkpoint, where the shape is torch.Size([128]) in current model.
size mismatch for conv3_t.weight: copying a param of torch.Size([63, 128]) from checkpoint, where the shape is torch.Size([128, 256, 1]) in current model.**

Help me in resolving this error.

I am using RTX 
![dimension mismatch](https://user-images.githubusercontent.com/50096409/69624673-75997300-1045-11ea-8928-7ed70ff6418c.png)
2080Ti with cuda10.0, pytorch-1.0
i have tried your docker image

**Comment by hoangcuongbk80** [comment]
Did you get the same error when test with the warehouse dataset [here](https://github.com/hoangcuongbk80/Object-RPE/tree/iliad)?

**Comment by vijaysamula** [comment]
I got the solution for that. RTX 2080 Ti needs Cuda 10 or higher. I am using Cuda 10 in docker and Cuda 9 in the user. Due to this, the error came, I think so. As of now, the error solved.
