### ISSUE TITLE
warehouse

### ISSUE THREAD

**Issue by Lcomerun** [hoangcuongbk80/Object-RPE#10]
Where can I get the warehouse datasets?

**Comment by hoangcuongbk80** [comment]
It contains 300GB of Data. We're figuring out where to upload.

**Comment by bophancong** [comment]
Hi. It's very nice work. Could you please share the way to make the warehouse datasets?

**Comment by hoangcuongbk80** [comment]
Hi.

To create the dataset: [LabelFusion](https://github.com/RobotLocomotion/LabelFusion)

To convert to a format for MaskRCNN: [script](https://github.com/hoangcuongbk80/python-tools/blob/master/labels_to_json_warehouse.py)

To conver to a format for DenseFusion: [script](https://github.com/hoangcuongbk80/python-tools/blob/master/labelfusion_to_mat.py)

**Comment by bophancong** [comment]
> Hi.
> 
> To create the dataset: [LabelFusion](https://github.com/RobotLocomotion/LabelFusion)
> 
> To convert to a format for MaskRCNN: [script](https://github.com/hoangcuongbk80/python-tools/blob/master/labels_to_json_warehouse.py)
> 
> To conver to a format for DenseFusion: [script](https://github.com/hoangcuongbk80/python-tools/blob/master/labelfusion_to_mat.py)

Thank for sharing.
