### ISSUE TITLE
How to make my own dataset?

### ISSUE THREAD

**Issue by lalaLin997** [hoangcuongbk80/Object-RPE#2]
Object-RPE/DenseFusion/datasets has a warehouse folder.
Could you provide the step of how to make own dataset?

**Comment by hoangcuongbk80** [comment]
Hi,

The warehouse dataset consists of over 20,000 RGB-D images extracted from 20 videos
captured by an ASUS Xtion PRO Live sensor.
The 6D poses of the objects and instance segmentation masks generated using the [LabelFusion](http://labelfusion.csail.mit.edu/).
Camera trajectories from a motion capture system developed by [Qualisys](https://www.qualisys.com).
