### ISSUE TITLE
What's the format of file "warehouse/train/via_region_data.json" of your warehouse dataset

### ISSUE THREAD

**Issue by yjdfly** [hoangcuongbk80/Object-RPE#4]
When I use the model trained on my own dataset to predict, there always occurred some error at "model.detect()". I think the format of dataset is not proper, but there is not 'via_region_data.json' in your data to refer. Can you provide that for me, thanks a lot.

**Comment by hoangcuongbk80** [comment]
Hi,

The file via_region_data.json is used for training Mask-RCNN.
You can find its format from the balloon example [here](https://github.com/matterport/Mask_RCNN/tree/master/samples/balloon). You should see a file name via_region_data.json in balloon_dataset.zip.
If you want to create a via_region_data.json for a dataset containing color images and label images. You can use [this script](https://github.com/hoangcuongbk80/python-tools/blob/master/labels_to_json_warehouse.py) or [this](https://github.com/hoangcuongbk80/python-tools/blob/master/labels_to_json_YCB_Video.py)

**Comment by yjdfly** [comment]
Thanks for your detailed answer. Now I can train the Mask-RCNN to get the trained model on YCB, but the test result is not  good. Do you also hold the mask_rcnn.h5 for YCB? Can you share?

**Comment by yjdfly** [comment]
@hoangcuongbk80 ,thanks for your detailed answer. Now I can train the Mask-RCNN to get the trained model on YCB, but the test result is not good. Do you also hold the mask_rcnn.h5 for YCB? Can you share?

**Comment by hoangcuongbk80** [comment]
We might consider sharing all trained models after our papers published.

**Comment by yjdfly** [comment]
Good Luck. I have solved that.
