### ISSUE TITLE
Some files missing

### ISSUE THREAD

**Issue by paradocx** [hoangcuongbk80/Object-RPE#7]
Excuse me.  I noticed some codes like 'open('/home/aass/catkin_ws/src/obj_pose_est/data/class_ids.txt') '  but I cannot match the source file. Looking forward to your reply.

**Comment by hoangcuongbk80** [comment]
Hi,

Please download and find class_ids.txt in the data folder as instruction [here](https://github.com/hoangcuongbk80/Object-RPE/tree/iliad)

**Comment by paradocx** [comment]
> Hi,
> 
> Please download and find class_ids.txt in the data folder as instruction [here](https://github.com/hoangcuongbk80/Object-RPE/tree/iliad)

Thanks for reply. I know that this is written for the  warehouse dataset at now. But I originally wanted to use this file _inference_ycb.py_.  If I don't change the YCB dataset, does that mean I can't use the code directly?

**Comment by hoangcuongbk80** [comment]
If you want to use the code for YCB dataset, some changes in the code are required. Unfortunately, I am on vacation until February. I hope I will have time to clean and update the code for easier use both datasets after vacation.
