### ISSUE TITLE
Dataset Images

### ISSUE THREAD

**Issue by aditya2592** [hoangcuongbk80/Object-RPE#9]
Hi, where can I download the images of the warehouse dataset?

**Comment by hoangcuongbk80** [comment]
Hi,

It is a large dataset (~300GB). I will figure out how to upload it to somewhere. At the moment you can download a video sample of the dataset [here](https://drive.google.com/file/d/1dzwcLOiakkSLiUoJXkPD8-QkIBFTJMXQ/view) or find more info in [iliad branch](https://github.com/hoangcuongbk80/Object-RPE/tree/iliad)

Good luck!

**Comment by aditya2592** [comment]
Thanks for your reply. In the meantime, is it possible to get the trained model on YCB video dataset? We needed the masks for our experiment.

**Comment by hoangcuongbk80** [comment]
We might consider sharing all trained models after our papers published.
Regarding training YCB video dataset, you can convert labled images to a json file for MaskRCNN input using [this script](https://github.com/hoangcuongbk80/python-tools/blob/master/labels_to_json_YCB_Video.py). Then follow the instruction [here](https://github.com/matterport/Mask_RCNN) to get your own trained model.
